# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9702888b7194ff9279885ee9e3db70ac5d64ec8bcac29698acc2a1eb9f2fabf5462575bfff720c53b9ce7f8ba70a3eb1f7a52412696aa4a8410f56745ef42ffa

test:
  secret_key_base: b05217606915d34c678a8bbc5c006f3dd1a286a4d60cbf69805144ebb45483f65ae6eb2ead1c9f059d660012165df493fb8a485e6b7ac2fee6aca80617a34420

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
